# This is a basic workflow to help you get started with Actions

name: CI_CD_Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "feature/*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install_dependecies:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"
            cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


  trigger_tests:
    #name: unit_test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: install_dependecies

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          python -m pip install pytest
          pytest
 
  create_pull_request:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: install_dependecies

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Create Pull Request
        id: create_pr
        run: |
          echo "PR_NUMBER=$(python python_scripts/create_pr.py --repo_slug ${{ github.repository }} --head_branch ${{ github.ref_name }} --base_branch dev --auth_token ${{ secrets.GH_TOKEN }})" >> $env:GITHUB_OUTPUT
      
  
  print_pr_number:
    runs-on: ubuntu-latest

    needs: [trigger_tests, create_pull_request]

    steps:
      - uses: actions/checkout@v4

      - name: "Print PR Number"
        run: |
         # echo ${{ github.job.create_pull_request.outputs.PR_NUMBER }}
         echo ${{ github.job.create_pull_request.steps.create_pr.outputs.PR_NUMBER }}
